# site settings
title: "H2O Jekyll Theme"
url: "" # your host
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'
keyword: ""
description: "A clean and delicate Jekyll theme."

# build settings
plugins: [jekyll-paginate]
exclude: ['node_modules', 'dev', 'dist', 'package.json', 'package-lock.json', '.gitignore', 'README.md', 'LICENSE']

paginate: 6
paginate_path: 'page:num'

# markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM